#!/bin/sh
# kbep is for kbe pack.  See also kbeu.
# It gzips-then-encrypts specified files.

if [ $# -lt 2 ]; then
	echo "Usage: $0 {key} {files ... }" 1>&2
	exit 1
fi

key=$1
shift

for filein; do
	if [ -f $filein ]; then
		gzip < $filein | kbe +$key > $filein.egz
	else
		echo "$0:  Can't find input file $filein." 1>&2
	fi
done
