#!/bin/sh

if [ $# -lt 2 ]; then
	echo "Usage: $0 {key} {files ... } " 1>&2
	exit 1
fi

key=$1
shift

for fileout
do
	if [ -f $fileout.egz ]; then
		kbe -$key < $fileout.egz | gunzip > $fileout
	else
		echo "$0:  Can't find input file $fileout.egz." 1>&2
	fi
done
