#!/usr/bin/perl

die "Usage: $0 {key}\n" if (@ARGV != 1);
$key = $ARGV[0];
$az  = "abcdefghijklmnopqrstuvwxyz";

$cr  = `echo $az | rct15 +$key`;
chomp $cr;

$len = length $az;
@azs = split //, $az;
@crs = split //, $cr;

$neq = 0;
$nne = 0;

for my $i (0 .. $len-1) {
	if ($azs[$i] eq $crs[$i]) {
		$neq++;
	}
	else {
		$nne++;
	}
}

printf "%-20s %u\n", $key, $neq;
