
rct17.exe: rc4.c rct17main.c ..\..\mmap\my_mmap.c
	cc /I..\..\mmap rc4.c rct17main.c ..\..\mmap\my_mmap.c -o rct17.exe

rc4.exe: rc4.c main.c ..\..\mmap\my_mmap.c
	cc /I..\..\mmap rc4.c main.c ..\..\mmap\my_mmap.c -o rc4.exe

